version: '3.3'

services:
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:$ELK_VERSION
    volumes:
      - type: bind
        source: ./config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: false
    ports:
      - "5601:5601"
    networks:
      - fourplusone

  client:
    build: ../client
    container_name: client
    ports:
      - "3000:3000"
    networks:
      - fourplusone

  api:
    build: ../api
    container_name: api
    ports:
      - "4000:4000"
    networks:
      - fourplusone


  kib01:
    image: docker.elastic.co/kibana/kibana:7.8.1
    container_name: kib01
    ports:
      - 15601:5601
    environment:
      ELASTICSEARCH_URL: http://10.132.0.10:9200
      ELASTICSEARCH_HOSTS: '["http://10.132.0.10:9200","http://10.132.0.11:9200","http://10.132.0.12:9200"]'
    networks:
      - fourplusone


networks:
  fourplusone:
    driver: bridge


